articles/urls.py
from django.urls import path
from . import views

app_name= "articles"
urlpatterns = [
    path('', views.articleslist, name="list"),
    path('<slug>',views.article_detail, name="detail"),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/' ,views.about),
    path('', views.home),
    path('articles/' , include('articles.urls'))
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    # in add thumbnail
    # add in author
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50] + ' ...'

articles/views.py
from django.shortcuts import render,HttpResponse
from . import models

# Create your views here.
def articleslist(request):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles':articles}
    return render(request, 'articles/articleslist.html', args)

def article_detail(request, slug):
        return HttpResponse(slug)

djangoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
      # return HttpResponse('Mohammad Javad Najafi')
      return render(request , 'about.html')

def home(request):
    # return HttpResponse('I Am Engeener Software! I love You Python! I Am Mohammad Javad Najafi, Thank You The Reading My Website!')
    return render(request , 'home.html')

articles/templates/articles/articleslist.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Articles</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<div class="container">
    <h1>Articles list</h1>
    {% for article in articles %}
    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
  </div>
</body>

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>about</title>
  </head>
  <body>
  <h1>about</h1>
  <p>ما جنگو را دوست داریم</p>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      <title>
    {%block title%}
  Articles
    {%endblock%}
    </title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <h2><a href="{% url 'articles:list' %}">LOGO</a></h2>
    <div class="wrapper">

    {% block content %}

    {%endblock%}

      </div>
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home</title>
  </head>
  <body>
  <h1>home</h1>
  <p>welcome to my Blog</p>
  </body>
</html>